### ISSUE TITLE
Classes need object equality testing functions.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/wattle#11]
**Prerequisite Issues**

- [x] #1 

**Overview of the Issue**

The decision tree splitting library [chainsaw](https://github.com/mikesiers/chainsaw) is using wattle. Something that has been noted during its unit test development is that object equality cannot be performed concisely. This is a fault of wattle. To fix this, wattle needs class equality testing functions for each class.

**Tasks to Complete Issue**

- [x] Determine how this should be implemented. Post it as a reply to this issue.
- [x] Update the class diagrams.
- [x] Update the class descriptions for issues #2, #3, #4, #9.

**Comment by mikesiers** [comment]
*How to Implement Object Equality Testing Function*

Two functions are needed. \_\_eq\_\_() and \_\_ne\_\_(). For more information, see [here](https://stackoverflow.com/questions/390250/elegant-ways-to-support-equivalence-equality-in-python-classes).

**Comment by mikesiers** [comment]
The work in this issue was completed by 14f74e9. It will be added later as part of a pull request.
