### ISSUE TITLE
Upload to PyPi

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/wattle#13]
**Overview of this Issue**

Multiple tasks need to be performed before wattle can be uploaded to PyPi. This includes a restructuring of the folder structure.

**Tasks to Close Issue**

- [x] Move src into root folder.
- [x] Create setup.cfg file
- [x] Create setup.py file.
- [x] Create release.
- [x] Upload to PyPi

**Comment by mikesiers** [comment]
https://pypi.python.org/pypi/wattle/1.00
