### ISSUE TITLE
Get more datasets for unit testing.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/wattle#16]
**Overview of this Issue**

The dataset which is currently used for unit testing (LOC_SDP.csv) is extremely simple. It only has two attributes, one of which is the class attribute. Therefore, many branches of execution are not being tested sufficiently. More datasets are required such that the unit testing can be run on a variety of datasets.

**Tasks to Close Issue**

Datasets with the following characteristics should be found. Additionally, each dataset should have at least 5 attributes.

- [ ] Only numeric attributes.
- [ ] Only categoric attributes.
- [ ] A mix of ≥ 3 numeric attributes and ≥ 3 categoric attributes.
- [ ] A dataset with at least 10000 records.
- [ ] A dataset with at least 3 possible class labels.
