### ISSUE TITLE
Constructors need to be designed.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/wattle#5]
**Prerequisite Issues**

- [x] #1 

**Overview of this Issue**

Constructors need to be designed for the following classes:

- Node
- Branch
- Tree

**Tasks to Close Issue**

- [x] Design the constructor function signatures. They can be posted as a reply to this issue.
- [x] Describe the constructor parameters.
- [x] Add them to the class diagrams.

**Comment by mikesiers** [comment]
Node(data, build, prune)

- data: The data corresponding to this node.
- build: Whether to build this node as part of the constructor.
- prune: Whether to prune this node after it is built. Cannot be True if the build flag is False.

Branch(parent, child, test_as_string)

- parent: The parent node.
- child: The child node.
- test_as_string: The test corresponding to this branch. Represented as a string.

Tree(data, build, prune, options)

- data: The data used at the root node. (The training data).
- build: whether to build the tree during object construction.
- prune: If the tree is build flag is True, this flag determines whether to prune the tree after it is built. This only applies to when the build process is performed as part of the constructor.
- options: Custom options presented in a dict. For example: {'min_num_records' : 12}.

**Comment by mikesiers** [comment]
The work needed to close this issue was completed in commit 3464c65.
