### ISSUE TITLE
Function needed which finds all possible split points.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/wattle#6]
**Prerequisite Issues**

- [x] #1 

**Overview of this Issue**

A function is needed which finds all possible splits points. This is needed so that splitting functions are easier to implement. The function can be added to the Node class. Since splits can be both categorical and numerical, the return type will need to accomodate for this somehow.

**Potential Challenges**

- Working out the best way to return a split which can be either categorical or numerical.
  - *Solution*: Return a dictionary. Each key is an attribute. Each element is a list of split values. The *user* of this function can check the attribute type themselves.

**Tasks to Close Issue**

- [x] Design a function signature. It can be posted as a reply to this issue.
- [x] Add the function to the class diagram for the Node class.
- [x] Design unit test(s) for this function. They can also be posted as a reply.
- [ ] Implement the unit tests.
- [ ] Implement the function.
- [ ] Ensure that the function passes its unit tests.
- [ ] Generate documentation.

**Comment by mikesiers** [comment]
*Function Signature*

get_possible_splits() : Dictionary&lt;List&gt;

Return a dictionary. Each key is an attribute. Each element is a list of split values. The user of this function can check the attribute type themselves. For example: 
{'Age' : [14, 16, 29, 31, 33], 'colour' : ['red', 'green', 'red', 'blue']}

**Comment by mikesiers** [comment]
*Unit Tests*

- Check that the splits are found from a simple example with a single numerical attribute.
- Check that the splits are found from a simple example with a single categorical attribute.
- Check that the splits are found from a simple example with both a numerical and categorical attribute.

**Comment by mikesiers** [comment]
This issue can now be considered part of Issue #2.
