### ISSUE TITLE
Function needed for getting split supports.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/wattle#7]
**Prerequisite Issues**

- [x] #1 

**Overview of this Issue**

A function should be added to the node class which gets the class supports of a potential split. The function will require a split as input. 

**Tasks to Close Issue**

- [x] Design a function signature. It can be posted in a reply to this issue.
- [x] Describe the function output and parameters.
- [x] Design unit tests. They can be posted in a reply to this issue.
- [ ] Implement the unit tests.
- [ ] Implement the function.
- [ ] Ensure that the function passes the unit tests.
- [ ] Generate documentation.

**Comment by mikesiers** [comment]
*Function Signature*

get_split_supports(split, data) : dict

return value: A dictionary where each key is the name of a class value, and each value is the support count for that class value.

-split: This can be represented as a dictionary. The key is the splitting attribute. For numerical splits, the value is the splitting value. For categorical splits, the value is empty.
-data: The data to split.

**Comment by mikesiers** [comment]
*Unit Tests*

- Check that a simple example produces the expected output for a categorical split.
- Check that a simple example produces the expected output for a numerical split.

**Comment by mikesiers** [comment]
This issue can now be considered a part of Issue #2.

**Comment by mikesiers** [comment]
Before this issue can be closed (and considered part of Issue #2, the class diagram for the Node class needs to be updated.
