### ISSUE TITLE
A lot of code would be cleaner if there was a standard split class.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/wattle#8]
**Prerequisite Issues**

- [x] #1 

**Overview of this Issue**

Some functions either return or require a test as input. Currently a test is represented as a dictionary such as {'attribute_one' : 30}. Places where tests are used are done so in a non-standard way. This can make code feel clumsy and unclean. Therefore, there should be a test class.

**Tasks to Close Issue**

- [x] Add a test class to the class diagrams.
- [x] Update the class diagrams so that `Test` is used when appropriate.
- [x] Describe the test class in detail. The description can be posted in a reply to this issue.
- [x] Update Issues #2, #3, and #4 to use `Test` when appropriate.
- [x] Create a new issue similar to #2, #3, and #4 but for the `Test` class.

**Comment by mikesiers** [comment]
*Class Description*

- type: A string which is either 'numerical' or 'categorical'.
- attribute: A string which is the name of the attribute to test.
- split_value: A float which is the splitting point. This is only used for Tests where `type='numerical'`
- Constructor: A default-like constructor.
- is_numerical() : Returns True if `type='numerical'`. False otherwise.
- is_categorical() : Returns True if `type='categorical'`. False otherwise.
- to_string() : Returns a string representation of the object.

**Comment by mikesiers** [comment]
All the tasks for this issue have been completed.
